BYTES_VERSION: bytes = b'crycript 2021.01.24'
STRING_VERSION: str = 'crycript 2021.01.24'
SUPPORTED_VERSIONS: list = []

MINIMUM_PASSWORD_LENGTH: int = 8
INVALID_PASSWORD_DELAY: int = 2

PBKDF2_ITERATIONS: int = 100_000
KEY_ENCRYPTION_ITERATIONS: int = 28

ENCRYPTED_FILENAME_ORIGINAL_CHARS: int = 2
ENCRYPTED_FILENAME_RANDOM_CHARS: int = 6
ENCRYPTED_FILENAME_CHARSET: str = 'abcdefghijklmnopqrstuvwxyz'
ENCRYPTED_FILE_EXTENSION: str = '.cry'

ENCRYPTION_BUFFER_SIZE: int = 100_000_000
STOP_SIGNAL: bytes = b":'("
